sudo: required
dist: trusty
language: node_js

node_js:
  - "4.2"

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@3.10.8;
  - npm install -g webpack
  - npm install

script:
- npm run test && npm run build

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - sqlinantes:8Usex84M6JTsUhBEymvhpm5w#team-blockchain
