sudo: required
dist: trusty
language: node_js

node_js:
  - "4.2"

cache:
  directories:
    - node_modules

before_install: 
	- if [[ `npm -v` != 2* ]]; then npm i -g npm@2; fi

install:
  - npm install -g webpack
  - npm install

script:
- npm run test && npm run build